spring:
    application:
        name: taorunhui-ai
    ai:
        dashscope:
            api-key: ${BAI_LIAN_API_KEY}
            chat:
                options:
                    model: qwen-plus-2025-04-28
            embedding:
                options:
                    model: text-embedding-v1
            rerank:
                options:
                    model: qwen3-rerank
        alibaba:
            python:
                tool:
                    enabled: false
        mcp:
            client:
                toolcallback:
                    enabled: true
                enabled: true
                name: taorunhui-mcp-client
                version: 1.0.0
                request-timeout: 30s
                type: SYNC
                sse:
                    connections:
                        pkulaw-mcp-law-search: # 连接名称，可以自定义
                            url: https://mcp.api-inference.modelscope.net
                            sseEndpoint: /d417183559de44/sse
                        output_with_docxpdf: # 连接名称，可以自定义
                            url: https://mcp.api-inference.modelscope.net
                            sseEndpoint: /15bdcc92006441/sse
                        Docx_MCP:
                            url: https://mcp.api-inference.modelscope.net
                            sseEndpoint: /17360824e6b74a/sse
                        bing-cn-mcp-server:
                            url: https://mcp.api-inference.modelscope.net
                            sseEndpoint: /a97a50c48f8a49/sse
                stdio:
                    servers-configuration: classpath:mcp-servers.json
    #                stdio:
    #                    servers-configuration: classpath:mcp-servers.json
    skills:
        # path: E:/study/AI/taorunhui-ai/src/main/resources/skills
        path: skills
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB

python:
    external:
        packages:
            path: D:/Software/anaconda3/Lib/site-packages

server:
    port: 7341

app:
    upload:
        dir: D:/tmp/taorunhui-uploads  # 默认项目根目录下的 uploads 文件夹

logging:
    level:
        com:
            alibaba:
                cloud:
                    ai:
                        agent: DEBUG